spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/workflowhub
    username: postgres
    password: admin12345
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        
